version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ems
      # MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-container
    ports:
      - "7079:7079"
    depends_on:
      - mysql
